export * from "./types";
export { studentService } from "./student.service";
export { parentService } from "./parent.service";
export { guardianService } from "./guardian.service";
export { studentHistoryService } from "./student-history.service";
export { transferService } from "./transfer.service";
export { alumniService } from "./alumni.service";
export { studentIdCardService } from "./student-id-card.service";
export { attendanceService } from "./attendance.service";
export { studentPortalService } from "./student-portal.service";
