import {
  LayoutDashboard,
  GraduationCap,
  Users,
  UserCog,
  UserPlus,
  DollarSign,
  Building2,
  FileText,
  ClipboardList,
  BarChart3,
  BookOpen,
  CalendarDays,
  Library,
  School,
  ClipboardCheck,
  Award,
  BadgePercent,
  ArrowLeftRight,
  GraduationCapIcon,
  CreditCard,
  Receipt,
  Wallet,
  PiggyBank,
  TrendingUp,
  BedDouble,
  Wrench,
  Package,
  Mail,
  Send,
  FileStack,
  FolderOpen,
  Megaphone,
  Bell,
  CalendarClock,
  BrainCircuit,
  Trophy,
  ShieldAlert,
  Activity,
  Shield,
  KeyRound,
  ScrollText,
  Cog,
  Stethoscope,
  Dumbbell,
  Clock,
  ShieldCheck,
} from "lucide-react";
import type { NavigationGroup } from "@/types";

export const navigation: NavigationGroup[] = [
  {
    label: "Akademik",
    items: [
      { label: "Tahun Ajaran", path: "/academic/years", icon: CalendarDays },
      { label: "Semester", path: "/academic/semesters", icon: CalendarDays },
      { label: "Kurikulum", path: "/academic/curriculum", icon: BookOpen },
      { label: "Mata Pelajaran", path: "/academic/subjects", icon: Library },
      { label: "Kelas", path: "/academic/classes", icon: School },
      { label: "Mata Pelajaran Kelas", path: "/academic/class-subjects", icon: BookOpen },
      { label: "Siswa Kelas", path: "/academic/class-students", icon: Users },
      { label: "Jadwal", path: "/academic/schedules", icon: CalendarClock },
      { label: "Jam Pelajaran", path: "/academic/periods", icon: Clock },
      { label: "Tugas", path: "/academic/assignments", icon: ClipboardList },
      { label: "Nilai", path: "/academic/grades", icon: Award },
      { label: "Rapor", path: "/academic/report-cards", icon: GraduationCap },
    ],
  },
  {
    label: "Siswa",
    items: [
      { label: "Data Siswa", path: "/students", icon: Users },
      { label: "Riwayat Siswa", path: "/students/history", icon: ScrollText },
      { label: "Kehadiran", path: "/students/attendance", icon: ClipboardCheck },
      { label: "Mutasi Siswa", path: "/students/transfers", icon: ArrowLeftRight },
      { label: "Alumni", path: "/students/alumni", icon: GraduationCapIcon },
      { label: "Kartu Pelajar", path: "/students/id-card", icon: BadgePercent },
    ],
  },
  {
    label: "Guru & Staf",
    items: [
      { label: "Guru", path: "/teachers", icon: UserCog },
      { label: "Staf", path: "/teachers/staff", icon: Users },
      { label: "Penugasan Mengajar", path: "/teachers/assignments", icon: ClipboardList },
      { label: "Kehadiran Guru", path: "/teachers/attendance", icon: ClipboardCheck },
      { label: "Cuti Guru", path: "/teachers/leave", icon: CalendarDays },
      { label: "Dokumen Guru", path: "/teachers/documents", icon: FileText },
    ],
  },
  {
    label: "PPDB",
    items: [
      { label: "Pendaftaran", path: "/ppdb/registrations", icon: UserPlus },
      { label: "Verifikasi", path: "/ppdb/verification", icon: ShieldCheck },
      { label: "Daftar Ulang", path: "/ppdb/re-registration", icon: ArrowLeftRight },
      { label: "Export Excel", path: "/ppdb/export-dapodik", icon: FileText },
    ],
  },
  {
    label: "Keuangan",
    items: [
      { label: "Jenis Tagihan", path: "/finance/fee-types", icon: CreditCard },
      { label: "Penagihan", path: "/finance/billing", icon: Receipt },
      { label: "Pembayaran", path: "/finance/payments", icon: Wallet },
      { label: "Transaksi", path: "/finance/transactions", icon: DollarSign },
      { label: "Beasiswa", path: "/finance/scholarships", icon: PiggyBank },
      { label: "Laporan Keuangan", path: "/finance/reports", icon: TrendingUp },
    ],
  },
  {
    label: "Kesiswaan",
    items: [
      { label: "Bimbingan & Konseling", path: "/development/counseling", icon: Stethoscope },
      { label: "Ekstrakurikuler", path: "/development/extracurricular", icon: Dumbbell },
      { label: "Prestasi", path: "/development/achievements", icon: Trophy },
      { label: "Pelanggaran", path: "/development/violations", icon: ShieldAlert },
    ],
  },
  {
    label: "Sarana & Prasarana",
    items: [
      { label: "Ruangan", path: "/facilities/rooms", icon: BedDouble },
      { label: "Aset", path: "/facilities/assets", icon: Package },
      { label: "Pemeliharaan", path: "/facilities/maintenance", icon: Wrench },
      { label: "Inventaris", path: "/facilities/inventory", icon: Building2 },
    ],
  },
  {
    label: "Administrasi",
    items: [
      { label: "Surat Masuk", path: "/administration/incoming", icon: Mail },
      { label: "Surat Keluar", path: "/administration/outgoing", icon: Send },
      { label: "Dokumen", path: "/administration/documents", icon: FileStack },
      { label: "Disposisi", path: "/administration/dispositions", icon: FolderOpen },
    ],
  },
  {
    label: "Komunikasi",
    items: [
      { label: "Pengumuman", path: "/communication/announcements", icon: Megaphone },
      { label: "Notifikasi", path: "/communication/notifications", icon: Bell },
      { label: "Kalender", path: "/communication/calendar", icon: CalendarClock },
    ],
  },
  {
    label: "Soal & Ujian",
    items: [
      { label: "Bank Soal", path: "/examinations/questions", icon: BrainCircuit },
      { label: "Ujian", path: "/examinations/exams", icon: ClipboardList },
      { label: "Jadwal Ujian", path: "/examinations/schedules", icon: CalendarClock },
      { label: "Sesi Ujian", path: "/examinations/sessions", icon: Activity },
      { label: "Peserta Ujian", path: "/examinations/participants", icon: Users },
      { label: "Hasil Ujian", path: "/examinations/results", icon: BarChart3 },
    ],
  },
  {
    label: "Laporan",
    items: [
      { label: "Laporan Akademik", path: "/reports/academic", icon: GraduationCap },
      { label: "Laporan Siswa", path: "/reports/students", icon: Users },
      { label: "Laporan Guru", path: "/reports/teachers", icon: UserCog },
      { label: "Laporan Keuangan", path: "/reports/finance", icon: DollarSign },
      { label: "Laporan Kehadiran", path: "/reports/attendance", icon: ClipboardCheck },
      { label: "Laporan Inventaris", path: "/reports/inventory", icon: Package },
    ],
  },
  {
    label: "Sistem",
    items: [
      { label: "Peran", path: "/system/roles", icon: Shield },
      { label: "Hak Akses", path: "/system/permissions", icon: KeyRound },
      { label: "Pengguna", path: "/system/users", icon: Users },
      { label: "Log Aktivitas", path: "/system/audit-logs", icon: ScrollText },
      { label: "Pengaturan", path: "/system/settings", icon: Cog },
    ],
  },
];

export const dashboardItem = {
  label: "Dasbor",
  path: "/dashboard",
  icon: LayoutDashboard,
} as const;
