import {
  LayoutDashboard,
  GraduationCap,
  Users,
  UserCog,
  UserPlus,
  DollarSign,
  Building2,
  FileText,
  ClipboardList,
  BarChart3,
  BookOpen,
  CalendarDays,
  Library,
  School,
  UserCheck,
  ClipboardCheck,
  Award,
  BadgePercent,
  ArrowLeftRight,
  GraduationCapIcon,
  CreditCard,
  Receipt,
  Wallet,
  PiggyBank,
  TrendingUp,
  BedDouble,
  Wrench,
  Package,
  Mail,
  Send,
  FileStack,
  FolderOpen,
  Megaphone,
  Bell,
  CalendarClock,
  BrainCircuit,
  Trophy,
  ShieldAlert,
  Activity,
  Shield,
  KeyRound,
  UsersRound,
  ScrollText,
  Cog,
  Stethoscope,
  Dumbbell,
  Clock,
  ShieldCheck,
} from "lucide-react";
import type { NavigationGroup } from "@/types";

export const navigation: NavigationGroup[] = [
  {
    label: "Academic",
    items: [
      { label: "Academic Year", path: "/academic/years", icon: CalendarDays },
      { label: "Semester", path: "/academic/semesters", icon: CalendarDays },
      { label: "Curriculum", path: "/academic/curriculum", icon: BookOpen },
      { label: "Subjects", path: "/academic/subjects", icon: Library },
      { label: "Classes", path: "/academic/classes", icon: School },
      { label: "Class Subjects", path: "/academic/class-subjects", icon: BookOpen },
      { label: "Class Students", path: "/academic/class-students", icon: Users },
      { label: "Schedules", path: "/academic/schedules", icon: CalendarClock },
      { label: "Periods", path: "/academic/periods", icon: Clock },
      { label: "Assignments", path: "/academic/assignments", icon: ClipboardList },
      { label: "Grades", path: "/academic/grades", icon: Award },
      { label: "Report Cards", path: "/academic/report-cards", icon: GraduationCap },
    ],
  },
  {
    label: "Students",
    items: [
      { label: "Student Data", path: "/students", icon: Users },
      { label: "Parents", path: "/students/parents", icon: UsersRound },
      { label: "Guardians", path: "/students/guardians", icon: UserCheck },
      { label: "Student History", path: "/students/history", icon: ScrollText },
      { label: "Attendance", path: "/students/attendance", icon: ClipboardCheck },
      { label: "Transfers", path: "/students/transfers", icon: ArrowLeftRight },
      { label: "Alumni", path: "/students/alumni", icon: GraduationCapIcon },
      { label: "Student ID Card", path: "/students/id-card", icon: BadgePercent },
    ],
  },
  {
    label: "Teachers & Staff",
    items: [
      { label: "Teachers", path: "/teachers", icon: UserCog },
      { label: "Staff", path: "/teachers/staff", icon: Users },
      { label: "Teaching Assignments", path: "/teachers/assignments", icon: ClipboardList },
      { label: "Teacher Attendance", path: "/teachers/attendance", icon: ClipboardCheck },
      { label: "Teacher Leave", path: "/teachers/leave", icon: CalendarDays },
      { label: "Teacher Documents", path: "/teachers/documents", icon: FileText },
    ],
  },
  {
    label: "PPDB",
    items: [
      { label: "Registration", path: "/ppdb/registrations", icon: UserPlus },
      { label: "Verification", path: "/ppdb/verification", icon: ShieldCheck },
      { label: "Selection", path: "/ppdb/selection", icon: ClipboardCheck },
      { label: "Re-registration", path: "/ppdb/re-registration", icon: ArrowLeftRight },
    ],
  },
  {
    label: "Finance",
    items: [
      { label: "Fee Types", path: "/finance/fee-types", icon: CreditCard },
      { label: "Billing", path: "/finance/billing", icon: Receipt },
      { label: "Payments", path: "/finance/payments", icon: Wallet },
      { label: "Transactions", path: "/finance/transactions", icon: DollarSign },
      { label: "Scholarships", path: "/finance/scholarships", icon: PiggyBank },
      { label: "Financial Reports", path: "/finance/reports", icon: TrendingUp },
    ],
  },
  {
    label: "Student Development",
    items: [
      { label: "Counseling", path: "/development/counseling", icon: Stethoscope },
      { label: "Extracurricular", path: "/development/extracurricular", icon: Dumbbell },
      { label: "Achievements", path: "/development/achievements", icon: Trophy },
      { label: "Violations", path: "/development/violations", icon: ShieldAlert },
    ],
  },
  {
    label: "Facilities",
    items: [
      { label: "Rooms", path: "/facilities/rooms", icon: BedDouble },
      { label: "Assets", path: "/facilities/assets", icon: Package },
      { label: "Maintenance", path: "/facilities/maintenance", icon: Wrench },
      { label: "Inventory", path: "/facilities/inventory", icon: Building2 },
    ],
  },
  {
    label: "Administration",
    items: [
      { label: "Incoming Letters", path: "/administration/incoming", icon: Mail },
      { label: "Outgoing Letters", path: "/administration/outgoing", icon: Send },
      { label: "Documents", path: "/administration/documents", icon: FileStack },
      { label: "Dispositions", path: "/administration/dispositions", icon: FolderOpen },
    ],
  },
  {
    label: "Communication",
    items: [
      { label: "Announcements", path: "/communication/announcements", icon: Megaphone },
      { label: "Notifications", path: "/communication/notifications", icon: Bell },
      { label: "Calendar", path: "/communication/calendar", icon: CalendarClock },
    ],
  },
  {
    label: "Question & Examination",
    items: [
      { label: "Question Banks", path: "/examinations/questions", icon: BrainCircuit },
      { label: "Exams", path: "/examinations/exams", icon: ClipboardList },
      { label: "Exam Schedules", path: "/examinations/schedules", icon: CalendarClock },
      { label: "Exam Sessions", path: "/examinations/sessions", icon: Activity },
      { label: "Exam Participants", path: "/examinations/participants", icon: Users },
      { label: "Exam Results", path: "/examinations/results", icon: BarChart3 },
    ],
  },
  {
    label: "Reports",
    items: [
      { label: "Academic Reports", path: "/reports/academic", icon: GraduationCap },
      { label: "Student Reports", path: "/reports/students", icon: Users },
      { label: "Teacher Reports", path: "/reports/teachers", icon: UserCog },
      { label: "Finance Reports", path: "/reports/finance", icon: DollarSign },
      { label: "Attendance Reports", path: "/reports/attendance", icon: ClipboardCheck },
      { label: "Inventory Reports", path: "/reports/inventory", icon: Package },
    ],
  },
  {
    label: "System",
    items: [
      { label: "Roles", path: "/system/roles", icon: Shield },
      { label: "Permissions", path: "/system/permissions", icon: KeyRound },
      { label: "Users", path: "/system/users", icon: Users },
      { label: "Audit Logs", path: "/system/audit-logs", icon: ScrollText },
      { label: "Settings", path: "/system/settings", icon: Cog },
    ],
  },
];

export const dashboardItem = {
  label: "Dashboard",
  path: "/dashboard",
  icon: LayoutDashboard,
} as const;
