export * from "./api";
export { default as AcademicYearPage } from "./pages/AcademicYearPage";
export { default as SemesterPage } from "./pages/SemesterPage";
export { default as CurriculumPage } from "./pages/CurriculumPage";
export { default as SubjectsPage } from "./pages/SubjectsPage";
export { default as ClassesPage } from "./pages/ClassesPage";
export { default as ClassSubjectsPage } from "./pages/ClassSubjectsPage";
export { default as ClassStudentsPage } from "./pages/ClassStudentsPage";
export { default as TeacherAssignmentsPage } from "../teachers-staff/pages/TeacherAssignmentsPage";
export { default as SchedulesPage } from "./pages/SchedulesPage";
export { default as PeriodsPage } from "./pages/PeriodsPage";
export { default as AssignmentsPage } from "./pages/AssignmentsPage";
export { default as GradesPage } from "./pages/GradesPage";
export { default as ReportCardsPage } from "./pages/ReportCardsPage";
